export const mockAppointments = [
  {
    id: "apt-201",
    client_name: "Atty. Fernando Zobel",
    client_email: "fzobel@ayala.ph",
    client_phone: "+63 917 888 1234",
    property_id: "1",
    property_title: "Ayala Alabang Estate",
    agent_id: "agent-1",
    agent_name: "Elena Rossi",
    appointment_date: "2026-09-08",
    appointment_time: "10:00 AM",
    appointment_type: "Site Visit",
    status: "REQUESTED",
    notes: "Client requested entry gate gatepass clearance for two vehicles. Bring site architectural plans."
  },
  {
    id: "apt-202",
    client_name: "Dr. Beatrice Ramos-Tan",
    client_email: "b.ramos@medclinic.ph",
    client_phone: "+63 920 901 4455",
    property_id: "2",
    property_title: "The Proscenium Penthouse",
    agent_id: "agent-1",
    agent_name: "Elena Rossi",
    appointment_date: "2026-09-09",
    appointment_time: "02:30 PM",
    appointment_type: "Document Signing",
    status: "CONFIRMED",
    notes: "Reservation agreement signing and issuance of earnest deposit receipt at Rockwell Club."
  },
  {
    id: "apt-203",
    client_name: "Engr. Mateo Villanueva",
    client_email: "mvillanueva@buildcon.ph",
    client_phone: "+63 918 333 7654",
    property_id: "3",
    property_title: "Forbes Park Modern Residence",
    agent_id: "agent-1",
    agent_name: "Elena Rossi",
    appointment_date: "2026-09-11",
    appointment_time: "11:00 AM",
    appointment_type: "Site Visit",
    status: "CONFIRMED",
    notes: "Structural ocular inspection with buyer's certified structural engineer."
  },
  {
    id: "apt-204",
    client_name: "Patricia Sy-Cojuangco",
    client_email: "psy@syinvest.com",
    client_phone: "+63 917 222 9901",
    property_id: "4",
    property_title: "One Serendra Garden Villa",
    agent_id: "agent-1",
    agent_name: "Elena Rossi",
    appointment_date: "2026-08-25",
    appointment_time: "03:00 PM",
    appointment_type: "Document Signing",
    status: "COMPLETED",
    notes: "Turnover deed execution completed. Key handover ceremony executed."
  },
  {
    id: "apt-205",
    client_name: "Gregory Delgado",
    client_email: "gdelgado@shipping.com",
    client_phone: "+63 917 111 4433",
    property_id: "5",
    property_title: "Tagaytay Ridge Sanctuary",
    agent_id: "agent-1",
    agent_name: "Elena Rossi",
    appointment_date: "2026-08-19",
    appointment_time: "01:00 PM",
    appointment_type: "Site Visit",
    status: "CANCELLED",
    notes: "Client rescheduled due to heavy monsoon rains in Tagaytay."
  },
  {
    id: "apt-206",
    client_name: "Michael Anthony Cruz",
    client_email: "mcruz@globalcap.sg",
    client_phone: "+65 9123 4567",
    property_id: "6",
    property_title: "Aurelia Residences Horizon Suite",
    agent_id: "agent-2",
    agent_name: "Alexander Sterling",
    appointment_date: "2026-09-10",
    appointment_time: "04:00 PM",
    appointment_type: "Online Consultation",
    status: "CONFIRMED",
    notes: "Zoom virtual walkthrough and 3D digital twin presentation."
  },
  {
    id: "apt-207",
    client_name: "Corazon Aquino-Dee",
    client_email: "cdee@deegroup.com",
    client_phone: "+63 917 444 8877",
    property_id: "7",
    property_title: "Greenhills West Contemporary Villa",
    agent_id: "agent-2",
    agent_name: "Alexander Sterling",
    appointment_date: "2026-09-12",
    appointment_time: "09:30 AM",
    appointment_type: "Site Visit",
    status: "REQUESTED",
    notes: "Inspection of interior master suite and garden drainage systems."
  }
];
