import React, { useState, useRef, useEffect } from 'react';
import { motion, useScroll, useTransform, useSpring } from 'framer-motion';
import {
  IconCompass,
  IconSparkles,
  IconSearch,
  IconAdjustmentsHorizontal,
  IconPlayerPlay,
  IconPlayerPause,
  IconReload,
  IconChevronDown,
  IconCamera,
  IconArrowUpRight,
  IconEye,
  IconLayersSubtract,
  IconBuildingSkyscraper
} from '@tabler/icons-react';

// Approach A Inpainted Raster Plates (Generated by Nano Banana Pro)
import plateSky from '../../sandbox/assets/parallax/plate-sky.jpg';
import plateVillaUnoccluded from '../../sandbox/assets/parallax/plate-villa-unoccluded.jpg';
import plateGates from '../../sandbox/assets/parallax/plate-gates.png';
import plateDriveway from '../../sandbox/assets/parallax/plate-driveway.png';

export default function PinnedDollyHeroShowcase() {
  const containerRef = useRef(null);
  const sentinelRef = useRef(null);

  // Simulation mode: 'scroll' tracks container scroll, 'slider' uses manual scrubber
  const [controlMode, setControlMode] = useState('slider');
  const [manualScrub, setManualScrub] = useState(0); // 0 to 1
  const [isPlaying, setIsPlaying] = useState(false);
  const [enableDoF, setEnableDoF] = useState(true);

  // Workspace Rule #1 & #3: Header visibility & manual override
  const [headerVisible, setHeaderVisible] = useState(true);
  const [searchSticky, setSearchSticky] = useState(false);
  const [manualHeaderOverride, setManualHeaderOverride] = useState(false);

  // Track page scroll on container
  const { scrollYProgress } = useScroll({
    target: containerRef,
    offset: ['start start', 'end end']
  });

  const smoothScroll = useSpring(scrollYProgress, { stiffness: 120, damping: 20 });
  const [scrollValue, setScrollValue] = useState(0);

  useEffect(() => {
    return smoothScroll.onChange((v) => {
      if (controlMode === 'scroll') {
        setScrollValue(v);
      }
    });
  }, [smoothScroll, controlMode]);

  // Auto-play loop for scrubber
  useEffect(() => {
    let animId;
    if (isPlaying && controlMode === 'slider') {
      let dir = 1;
      const step = () => {
        setManualScrub((prev) => {
          let next = prev + 0.006 * dir;
          if (next >= 1) {
            next = 1;
            dir = -1;
          } else if (next <= 0) {
            next = 0;
            dir = 1;
          }
          return next;
        });
        animId = requestAnimationFrame(step);
      };
      animId = requestAnimationFrame(step);
    }
    return () => {
      if (animId) cancelAnimationFrame(animId);
    };
  }, [isPlaying, controlMode]);

  // Workspace Rule #2: Sentinel getBoundingClientRect tracking
  useEffect(() => {
    const handleScrollCheck = () => {
      if (!sentinelRef.current) return;
      const rect = sentinelRef.current.getBoundingClientRect();
      // When sentinel passes the 80px header threshold
      if (rect.top <= 80) {
        setSearchSticky(true);
        if (!manualHeaderOverride) {
          setHeaderVisible(false);
        }
      } else {
        setSearchSticky(false);
        setHeaderVisible(true);
      }
    };

    window.addEventListener('scroll', handleScrollCheck, { passive: true });
    return () => window.removeEventListener('scroll', handleScrollCheck);
  }, [manualHeaderOverride]);

  // Active Progress: either manual scrub or container scroll
  const p = controlMode === 'slider' ? manualScrub : scrollValue;

  // Approach A Mathematical Transformations (Concentric Push-In Dolly)
  // 1. Layer 0: Celestial Sky (Anchored, subtle scale)
  const skyScale = 1 + 0.08 * p;
  const skyY = -28 * p;

  // 2. Layer 1: Unoccluded Villa (Revealed behind the gates, focal target)
  const villaScale = 1 + 0.46 * p;
  const villaY = -36 * p;

  // 3. Layer 2: Isolated Gates & Perimeter (Splits open outward & fades)
  const gateSplit = p > 0.15 ? (p - 0.15) * 420 : 0;
  const gateScale = 1 + 0.95 * p;
  const gateOpacity = Math.max(0, 1 - p * 1.8);

  // 4. Layer 3: Foreground Cobblestone & Vehicle (Sweeps down, scales up, DoF blur)
  const roadScale = 1 + 1.85 * p;
  const roadY = 120 * p;
  const roadBlur = enableDoF ? 9 * p : 0;
  const roadOpacity = Math.max(0, 1 - p * 2.1);

  // Virtual Camera Distance from Villa Entry (45.0 meters down to 12.0 meters)
  const cameraDistance = (45.0 - p * 33.0).toFixed(1);

  return (
    <div ref={containerRef} className="space-y-8 relative">
      {/* Header Info */}
      <div className="flex flex-col md:flex-row md:items-end justify-between gap-6">
        <div>
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full text-xs font-semibold uppercase tracking-wider bg-amber-500/10 text-amber-800 border border-amber-500/20 mb-3">
            <IconSparkles className="w-3.5 h-3.5 text-amber-600" />
            Approach A • Inpainted Multi-Plate Architecture
          </div>
          <h2 className="text-2xl sm:text-3xl font-extrabold font-display text-[#174849] tracking-tight">
            Approach A: Pinned Multi-Plate Scroll Dolly
          </h2>
          <p className="text-sm text-stone-600 mt-2 max-w-3xl leading-relaxed">
            Directly testing Approach A in the sandbox. Combines 4 raster plates generated by Nano Banana Pro (Celestial Sky, Unoccluded Villa, Isolated Gates, and Cobblestone Driveway) to execute a continuous camera push-in from the gates into the villa.
          </p>
        </div>

        {/* Control Mode Switcher */}
        <div className="flex p-1 rounded-xl bg-stone-200/70 border border-stone-300/60 shadow-xs self-start md:self-auto">
          <button
            onClick={() => { setControlMode('slider'); setIsPlaying(false); }}
            className={`px-4 py-2 rounded-lg text-xs font-bold tracking-wider transition-all uppercase cursor-pointer ${
              controlMode === 'slider'
                ? 'bg-[#174849] text-white shadow-sm'
                : 'text-stone-700 hover:text-stone-900 hover:bg-stone-300/50'
            }`}
          >
            Interactive Scrubber
          </button>
          <button
            onClick={() => { setControlMode('scroll'); setIsPlaying(false); }}
            className={`px-4 py-2 rounded-lg text-xs font-bold tracking-wider transition-all uppercase cursor-pointer ${
              controlMode === 'scroll'
                ? 'bg-[#174849] text-white shadow-sm'
                : 'text-stone-700 hover:text-stone-900 hover:bg-stone-300/50'
            }`}
          >
            Page Scroll Track
          </button>
        </div>
      </div>

      {/* THE PINNED STAGE VIEWPORT */}
      <div className="relative w-full rounded-2xl overflow-hidden border border-stone-800 bg-[#060D10] shadow-2xl">
        {/* Simulated Top Header (Workspace Rule #1 & #3) */}
        <motion.div
          animate={{
            y: headerVisible ? 0 : -80,
            opacity: headerVisible ? 1 : 0
          }}
          transition={{ duration: 0.25 }}
          className="absolute top-0 left-0 right-0 h-[80px] z-40 bg-stone-950/80 backdrop-blur-md border-b border-white/10 px-6 flex items-center justify-between pointer-events-none"
        >
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-lg bg-emerald-500 flex items-center justify-center text-stone-950 font-bold font-display">
              D
            </div>
            <span className="text-white font-display font-bold tracking-tight text-lg">
              DAHLIA ENCLAVE
            </span>
          </div>
          <div className="text-xs font-mono text-stone-400 hidden sm:block">
            Main Header • Auto-hides on Sentinel Crossing (Rule #1)
          </div>
        </motion.div>

        {/* Circular Manual Override Button (Workspace Rule #3) */}
        <button
          onClick={() => {
            setManualHeaderOverride(!manualHeaderOverride);
            setHeaderVisible(!headerVisible);
          }}
          aria-label="Summon Header"
          className="absolute top-4 right-4 z-50 w-11 h-11 rounded-full bg-white text-stone-900 shadow-xl flex items-center justify-center hover:scale-105 transition-transform cursor-pointer"
          title="Manual Header Summon Override (Rule #3)"
        >
          <IconCompass size={20} className={manualHeaderOverride ? 'text-amber-600 animate-spin' : 'text-[#174849]'} />
        </button>

        {/* 16:9 Viewport Stage */}
        <div className="relative w-full aspect-[16/9] min-h-[420px] max-h-[640px] overflow-hidden flex items-center justify-center select-none">
          {/* Layer 0: Celestial Sky (Nano Banana Pro inpainting) */}
          <motion.div
            style={{
              scale: skyScale,
              y: skyY,
              transformOrigin: '48% 54%'
            }}
            className="absolute inset-0 w-full h-full z-[1] pointer-events-none transform-gpu"
          >
            <img src={plateSky} alt="Celestial Sky Background" className="w-full h-full object-cover" />
          </motion.div>

          {/* Layer 1: Unoccluded Villa Architecture (Inpainted courtyard & lower stone facade) */}
          <motion.div
            style={{
              scale: villaScale,
              y: villaY,
              transformOrigin: '48% 54%'
            }}
            className="absolute inset-0 w-full h-full z-[2] pointer-events-none transform-gpu"
          >
            <img src={plateVillaUnoccluded} alt="Unoccluded Villa Architecture" className="w-full h-full object-cover" />
          </motion.div>

          {/* Layer 2: Isolated Gates & Perimeter (Splits open outward past camera) */}
          <motion.div
            style={{
              x: -gateSplit,
              scale: gateScale,
              opacity: gateOpacity,
              transformOrigin: '48% 54%'
            }}
            className="absolute inset-0 w-full h-full z-[3] pointer-events-none transform-gpu"
          >
            <img src={plateGates} alt="Isolated Perimeter Gates" className="w-full h-full object-cover" />
          </motion.div>

          {/* Layer 3: Foreground Cobblestone & Sedan (Sweeps down with DoF blur) */}
          <motion.div
            style={{
              scale: roadScale,
              y: roadY,
              opacity: roadOpacity,
              filter: roadBlur > 0 ? `blur(${roadBlur}px)` : 'none',
              transformOrigin: '48% 54%'
            }}
            className="absolute inset-0 w-full h-full z-[4] pointer-events-none transform-gpu"
          >
            <img src={plateDriveway} alt="Cobblestone Road and Sedan" className="w-full h-full object-cover" />
          </motion.div>

          {/* HUD Watermark */}
          <div className="absolute top-24 left-6 z-30 px-3 py-1.5 bg-black/65 backdrop-blur-md rounded-lg border border-white/15 text-[11px] font-mono text-amber-400 flex items-center gap-2">
            <span className="w-2 h-2 rounded-full bg-amber-400 animate-ping" />
            <span>CAMERA DISTANCE: {cameraDistance}m • DOLLY PUSH: {(p * 100).toFixed(0)}%</span>
          </div>

          {/* Hidden Sentinel Marker for Rule #2 */}
          <div ref={sentinelRef} className="absolute bottom-10 left-0 w-full h-1 pointer-events-none opacity-0" />
        </div>

        {/* STICKY SEARCH BOX (WORKSPACE RULES #1, #2, #6) */}
        <motion.div
          animate={{
            borderRadius: searchSticky ? '0px' : '16px',
            y: manualHeaderOverride ? 80 : 0
          }}
          transition={{ duration: 0.2 }}
          className={`w-full p-4 bg-stone-900/95 backdrop-blur-md border-t border-stone-800 transition-all ${
            searchSticky ? 'sticky top-0 z-40 shadow-2xl' : 'relative'
          }`}
        >
          <div className="max-w-5xl mx-auto flex flex-col sm:flex-row items-center gap-3">
            {/* Search Input (Strictly h-[54px] per Rule #6) */}
            <div className="relative flex-1 w-full">
              <IconSearch className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-stone-400" />
              <input
                type="text"
                placeholder="Search estate villas, penthouses, or lots..."
                className="w-full h-[54px] pl-12 pr-4 bg-stone-800 text-white rounded-xl border border-stone-700 text-sm focus:outline-none focus:border-amber-400 placeholder:text-stone-400"
              />
            </div>

            {/* Category Dropdown (Strictly h-[54px] per Rule #6) */}
            <div className="relative w-full sm:w-48">
              <select className="w-full h-[54px] px-4 bg-stone-800 text-white rounded-xl border border-stone-700 text-sm appearance-none cursor-pointer focus:outline-none focus:border-amber-400">
                <option>All Residences</option>
                <option>Duplex Villas</option>
                <option>Custom Enclave</option>
              </select>
              <IconChevronDown className="absolute right-4 top-1/2 -translate-y-1/2 w-4 h-4 text-stone-400 pointer-events-none" />
            </div>

            {/* Search CTA Button (Strictly h-[54px] per Rule #6) */}
            <button
              aria-label="Search Properties"
              className="w-full sm:w-auto h-[54px] px-7 rounded-xl bg-amber-500 hover:bg-amber-400 text-stone-950 font-bold text-sm tracking-wide transition-colors flex items-center justify-center gap-2 cursor-pointer shadow-md shrink-0"
            >
              <span>Explore</span>
              <IconArrowUpRight size={18} />
            </button>
          </div>
        </motion.div>
      </div>

      {/* Scrub & Simulation Controls */}
      <div className="p-4 rounded-xl bg-stone-900 text-white border border-stone-800 flex flex-col sm:flex-row items-center gap-4 shadow-md">
        <div className="flex items-center gap-2">
          <button
            onClick={() => setIsPlaying(!isPlaying)}
            disabled={controlMode !== 'slider'}
            className={`w-10 h-10 rounded-lg transition-all flex items-center justify-center font-bold cursor-pointer ${
              controlMode === 'slider'
                ? 'bg-amber-500 hover:bg-amber-400 text-black'
                : 'bg-stone-800 text-stone-600 cursor-not-allowed'
            }`}
            aria-label={isPlaying ? 'Pause' : 'Play'}
          >
            {isPlaying ? <IconPlayerPause size={18} /> : <IconPlayerPlay size={18} />}
          </button>

          <button
            onClick={() => { setManualScrub(0); setIsPlaying(false); }}
            className="w-10 h-10 rounded-lg bg-white/10 hover:bg-white/20 text-white transition-all flex items-center justify-center cursor-pointer"
            aria-label="Reset"
          >
            <IconReload size={18} />
          </button>
        </div>

        <div className="flex-1 w-full flex items-center gap-3">
          <span className="text-[11px] font-mono text-stone-400">Gate (0%)</span>
          <input
            type="range"
            min="0"
            max="1"
            step="0.005"
            value={manualScrub}
            disabled={controlMode !== 'slider'}
            onChange={(e) => {
              setManualScrub(parseFloat(e.target.value));
              setIsPlaying(false);
            }}
            className="flex-1 accent-amber-400 h-2 bg-white/10 rounded-lg cursor-pointer disabled:opacity-40"
          />
          <span className="text-[11px] font-mono text-amber-400 font-bold min-w-[50px]">
            {(p * 100).toFixed(0)}%
          </span>
          <span className="text-[11px] font-mono text-stone-400">House (100%)</span>
        </div>

        <div className="flex items-center gap-4 text-xs font-mono">
          <label className="flex items-center gap-2 cursor-pointer text-stone-300 select-none">
            <input
              type="checkbox"
              checked={enableDoF}
              onChange={(e) => setEnableDoF(e.target.checked)}
              className="accent-amber-500"
            />
            <span>DoF Optical Blur</span>
          </label>
        </div>
      </div>
    </div>
  );
}
